#Gel electrophoresis is an analysis method implemented in all disciplines of life sciences. 
# The results of gel electrophoresis indicate the relative sizes of fragments, which is useful for restriction mapping and analyzing PCR fragments. 
#1. Take an arbitrary DNA sequence from the NCBI (National Center for Biotechnology), between 1000 and 3000 nucleotides (letters).
#2. Take 10 random samples from this sequence, between 100-3000 bases.
#3. Store these samples in an array.
#4. Simulate the migration of these DNA segments on the electrophoresis gel, based on their molecular weights - however, their length should be sufficient for this exercise (show a visual representation).

import random
import matplotlib.pyplot as plt

master_seq = "TGCTCGTCTATACTTTCACAATCTTGACCTGCACGGCAAAGAGACGCTTCTTGTGGAGCTCGACAACGCAACAACGCGACGGATCTACGTCACAGCGAGTATAGTGAAAACGAAGTTGCTGACGGCGGAAGCGACATAGGGATCTGTCAGTTGTCATTCGCGAAAAACATCCGTCCCCGAGGGGGACAGTCACTGACGCGGTTTTGTAGAAGCCTAGGGGAACAGGTTAGTTTGAGTAGCTTAAGAATGTAAATTCTGGGATTATAGTGTAGTAATCTCTAATTAACGGTGACGGTTTTAAGACAGGTCTTCGCAAAATCAAGCGGGGTGATTTCAACAGATTTTGCTGATGGTTTAGGCGTACAATGCCCTGAAGAATAATTAAGAAAATAGCACTCCTCGTCGCCTAGAATTACCTACCGGCGTCCACCATACCTTCGATTATCGCGCCCACTCTCCCATTAGTCGGCACAGGTGGATGTGTTGCGATAGCCCGCTAAGATATTCTAAGGCGTAACGCAGATGAATATTCTACAGAGTTGCCATAGGCGTTGAACGCTTCACGGACGATAGGAATTTGCGTATAGAGCGGGTCATCGAAGGGTTATACACTCGTAGTTAACATCTAGCCCGGCTCTATCAGTACACCAGTGCCTTGAATGACATACTCATCATTAAACTTTCTCAACAGTCAAACGACCAAGTGCATTTCCAAGGAGTGCGATGGAGATTCATTCTCTCGCCAGCACTGTAATAGGCACTAAAAGAGTGATGATAATCATGAGTGCCGTGCTAAGACGGTGTCGGAACAAAGCGGTCTTACGGTCAGTCGTATTTCCTCTCGAGTCCCGTCCAGTTGAGCGTATCACTCCCAGTGTACTAGCAAGCCGAGAAGGCTGTGCTTGGAGTCAATCGGATGTAGGATGGTCTCCAGACACCGGGCCACCACTCTTCACGCCTAAAGCATAAACGTCGAGCAGTCATGAAAGTCTTAGTACCGGACGTGCCGTTTCACTGCGAATATTACCTGAAGCTGTACCGTTATTGCGGAGCAAAGATGCAGTGCTGCTCTTATCATATTTGTATTGACGACAGCCGCCTTCGCGGTTTCCTCAGACACTTAAGAATAAGGGCTTATTGTAGGCAGAGGCACGCCCTTTTAGTGGCTGCGGCAAAATATCTTCGGATCCCCTTGTCTAACCAAATTAATCGAATTCTCTCATTTAAGACCCTAATATGTCATCATTAGTGTTTAAATGCCACCCCGAAAATACCGCCTAGAAATGTCTATGATTGGTCCACTAAAGTTGATTAAAACGACTGCTAAATCCGCGTGATAGGGCATTTGAAGTTTAATTTTGTATCGCAAGGTACTCCCGATCTTAATGGATGGCCGGAAGTGGTACGGATGCAATAAGCGCGGGTGAGAGGGTAATTAGGCGCGTTCACCTACGCTACGCTAACGGGCGATTCTATAAGAATGCACATTGCGTCGATTCATAAGATGTCTCGACCGCATGCGCAACTTGTGAAGTGTCTACTATCCCTAAGCGCATATCTCGCACAGTAACCCCCGAATATGTCGGCATCTGATGTTACCCGGGTTGAGTTAGTGTTGAGCTCACGGAACTTATTGTATGAGTAGAGATTTGTAAGAGCTGTTAGTTAGCTCGCTCAGCTAATAGTTGCCCACACAACGTCAAAATTAGAGAACGGTCGTAACATTATCGGTGGTTCTCTAACTACTATCAGTACCCACGACTCGACTCTGCCGCAGCTACGTATCGCCTGAAAGCCAGTCAGCGTTAAGGAGTGCTCTGACCAGGACAACACGCGTAGTGAGAGTTACATGTTCGTTGGGCTCTTCCGACTCGGACCTGAGTTGGCCAACGACCCACTTGAGGTCTGAGCCCCGGTGATGAGAAGTATGCATCTCGTTCCCGCAGCTTGCCAGCACTTTCAGAATCATGGCGTGCATGGTAGAATGACTCTTATAACGGACTTCGACATGGCAATATCCCCCCCTTTCAACTTCTAGAGGAGAAAAGTATTGACATGAGCGCTCCCGGCACAACGGCCAAAGAAGTCTCCAATTTCTTATTTCCGAATGACATGCGTCTCCTTGCGGGTAAATCGCCGACCGCAAAACTTAGGAGCCAGGGGGAACAGATAGGTCTAATTAGCTTAAGGGAGTAAATCCTGGGATCGTTCAGTTGTAACCATATACTTACGCTGGGGCTTCTCCGGCGGATTTTTACTGTCACCAACCACGAGATTTGAAGTAAACCAATTGAGCACATAGCCGCGCTATCCGACAATCTCCAAATTATAACATACCGTTCCATGAAGGCCAGAATTACTTACCGGCCCTTTCCATGCGTGCGCCATACCCCCCCACTCCCCCGCTTATCCGTCCGAGGGGAGAGTGTGCGATCCTCCGTTAAGATATTCTTACGTATGACGTAGCTATGTATTTTGCAGAGGTAGCGAACGCGTTGAA"
seq_length = len(master_seq)
print(f"DNA sequence length: {seq_length} bp")

num_fragments = 10
fragments = []
fragment_lengths = []

for i in range(num_fragments):
    frag_length = random.randint(100, seq_length)
    start_index = random.randint(0, seq_length - frag_length)
    fragment = master_seq[start_index:start_index + frag_length]
    
    fragments.append(fragment)
    fragment_lengths.append(len(fragment))

print("Fragment lengths (bp):", fragment_lengths)

K = 1000
migration_distances = [K / length for length in fragment_lengths]

plt.figure(figsize=(6, 8))
lane = 1
for i, dist in enumerate(migration_distances):
    plt.plot([lane - 0.4, lane + 0.4], [dist, dist], color='blue', linewidth=8)
    plt.text(lane + 0.5, dist, f"{fragment_lengths[i]} bp", va='center')

plt.gca().invert_yaxis()
plt.title("Simulated Gel Electrophoresis")
plt.xlabel("Lane")
plt.ylabel("Migration Distance (arbitrary units)")
plt.xlim(0, 2)
plt.ylim(0, max(migration_distances) + 2)
plt.show()
